matrix:
  include:
    - language: objective-c
      os: osx
      install:
          - if [[ "$(uname -s)" == 'Darwin' ]]; then
             pyenv install 2.6.9;
             pyenv global 2.6.9;
            fi
          - export PYENV_ROOT="${HOME}/.pyenv"
          - if [ -d "${PYENV_ROOT}" ]; then
             export PATH="${PYENV_ROOT}/bin:${PATH}";
             eval "$(pyenv init -)";
            fi
          
    - language: objective-c
      os: osx
      install:
          - if [[ "$(uname -s)" == 'Darwin' ]]; then
             pyenv install 2.5.6;
             pyenv global 2.5.6;
            fi
          - export PYENV_ROOT="${HOME}/.pyenv"
          - if [ -d "${PYENV_ROOT}" ]; then
             export PATH="${PYENV_ROOT}/bin:${PATH}";
             eval "$(pyenv init -)";
            fi
 
    - language: objective-c
      os: osx
      install:
        - if [[ "$(uname -s)" == 'Darwin' ]]; then
           brew update;
           brew install python;
          fi
 
    - language: perl
      os: linux
      install:
        - export DEBIAN_FRONTEND=noninteractive
        - sudo apt-add-repository -y ppa:fkrull/deadsnakes
        - sudo apt-get update
        - sudo apt-get -y install python2.5
        - sudo alias python=python2.5
        - sudo alias python2=python2.5
        - sudo alias pydoc=pydoc2.5
        - sudo alias pygettext=pygettext2.5
 
    - language: python
      python: '2.6'
      os: linux
 
    - language: python
      python: '2.7'
      os: linux

script:
  - python --version
  - cd ./scripts
  - python initialize.py
  - python build.py -t
  - cd ../RUNNABLE
  - python utf.py -a
