matrix:
  include:
    - language: objective-c
      os: osx

    - language: python
      os: linux
      
install:
    - if [[ "$(uname -s)" == 'Darwin' ]]; then
       brew tap homebrew/versions;
       brew install python25;
      fi
      
script:
  - python --version
  - cd ./scripts
  - python initialize.py
  - python build.py -t
  - cd ../RUNNABLE
  - python utf.py -a
