os:
  - linux
  
language: python
python:
   - "2.5"  
   - "2.6"
   - "2.7"
install:
    - if [[ "$(uname -s)" == 'Darwin' ]]; then
       brew update;
       brew install python;
      fi
      
script:
  - python --version
  - cd ./scripts
  - python initialize.py
  - python build.py -t
  - cd ../RUNNABLE
  - python utf.py -a
