language: objective-c

env:
  global:
    - CXX=clang++

before_install:
  - brew update
  - brew install python

script:
  - python --version
  - cd ./scripts
  - python initialize.py
  - python build.py -t
  - cd ../RUNNABLE
  - python utf.py -a
