matrix:
  include:
    - language: objective-c
      os: osx

    - language: python2.6
      os: linux

    - language: python2.7
      os: linux
      
install:
    - if [[ "$(uname -s)" == 'Darwin' ]]; then
       brew update;
       brew install pyenv;
      fi
      
script:
  - python --version
  - cd ./scripts
  - python initialize.py
  - python build.py -t
  - cd ../RUNNABLE
  - python utf.py -a
