matrix:
  include:
    - language: objective-c
      os: osx
      install:
          - travis_fold:start:INSTALL folding starts
          - if [[ "$(uname -s)" == 'Darwin' ]]; then
             pyenv install -v 2.6.9;
             pyenv global 2.6.9;
            fi
          - export PYENV_ROOT="${HOME}/.pyenv"
          - if [ -d "${PYENV_ROOT}" ]; then
             export PATH="${PYENV_ROOT}/bin:${PATH}";
             eval "$(pyenv init -)";
            fi
          - travis_fold:end:INSTALL folding ends
    - language: objective-c
      os: osx
      install:
          - echo "travis_fold:start:INSTALL folding starts"
          - if [[ "$(uname -s)" == 'Darwin' ]]; then
             pyenv install -v 2.5.6;
             pyenv global 2.5.6;
            fi
          - export PYENV_ROOT="${HOME}/.pyenv"
          - if [ -d "${PYENV_ROOT}" ]; then
             export PATH="${PYENV_ROOT}/bin:${PATH}";
             eval "$(pyenv init -)";
            fi
          - echo "travis_fold:end:INSTALL folding ends"
 
    - language: objective-c
      os: osx
      install:
        - if [[ "$(uname -s)" == 'Darwin' ]]; then
           brew update;
           brew install python;
          fi
 
    - language: perl
      os: linux
      install:
        - git clone https://github.com/yyuu/pyenv.git ~/.pyenv
        - export PYENV_ROOT="$HOME/.pyenv"
        - export PATH="$PYENV_ROOT/bin:$PATH"
        - eval "$(pyenv init -)"
        - exec $SHELL
        - pyenv install -v 2.5.6;
 
    - language: python
      python: '2.6'
      os: linux
 
    - language: python
      python: '2.7'
      os: linux

script:
  - python --version
  - cd ./scripts
  - python initialize.py
  - python build.py -t
  - cd ../RUNNABLE
  - python utf.py -a
