environment:
  matrix:
    - PYTHON: "C:/Python26"
    - PYTHON: "C:/Python27"
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  - cd scripts
  - "%PYTHON%/python.exe initialize.py"
  - "%PYTHON%/python.exe build.py -t"

test_script:
  - cd ../RUNNABLE
  - "%PYTHON%/python.exe utf.py -a"
