environment:
  matrix:
    - PYTHON: "C:/Python26"
    - PYTHON: "C:/Python27"
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  - cd scripts
  - python initialize.py
  - python build.py -t

test_script:
  - cd ../RUNNABLE
  - python utf.py -a
