environment:
  matrix:
    - PYTHON: "C:/Python26"
    - PYTHON: "C:/Python27"
init:
  - "ECHO %PYTHON%"

test_script:
  - cd scripts
  - python initialize.py
  - python build.py -t
  - cd ../RUNNABLE
  - python utf.py -a
