build: false

environment:
  matrix:
    - PYTHON: "C:/Python26"
    - PYTHON: "C:/Python27"

platform:
- x86
- x64

test_script:
  - ps: cd scripts
  - python initialize.py
  - python build.py -t
  - ps: cd ../RUNNABLE
  - python utf.py -a
